apiVersion: apps/v1
kind: Deployment
metadata:
  name: trend-store
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trend-store
  template:
    metadata:
      labels:
        app: trend-store
    spec:
      containers:
      - name: trend-store
        image: dhinesh5799/trend-store:latest
        ports:
        - containerPort: 80
